name = "TriDiagBlock"
uuid = "e294871a-52ed-424c-aac5-512b15cb83b5"
authors = ["David Jin <jindavid@mit.edu>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.11.0"
