name = "BlockStructuredSolvers"
uuid = "e294871a-52ed-424c-aac5-512b15cb83b5"
license = "MIT"
authors = ["David Jin <jindavid@mit.edu>", "Sungho Shin <sushin@mit.edu>"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
CUDA = "5.6.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
