name = "BlockStructuredSolvers"
uuid = "e294871a-52ed-424c-aac5-512b15cb83b5"
license = "MIT"
authors = ["David Jin <jindavid@mit.edu>", "Alexis Montoison <amontoison@anl.gov>", "Sungho Shin <sushin@mit.edu>"]
version = "0.1.0"

[deps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
AMDGPU = "2.0.1"
CUDA = "5.8.2"
LinearAlgebra = "1.10"
SparseArrays = "1.10"
julia = "1.10"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
