name: CI

on:
  push:
    branches:
      - main
      - proper_strucutre
  pull_request:
    branches:
      - main
      - proper_strucutre

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.9'  # Use the latest stable Julia version

      - name: Cache Julia artifacts
        uses: actions/cache@v3
        with:
          path: ~/.julia/artifacts
          key: artifacts-${{ runner.os }}-${{ hashFiles('**/Project.toml') }}-${{ hashFiles('**/Manifest.toml') }}
          restore-keys: artifacts-${{ runner.os }}-

      - name: Cache Julia packages
        uses: actions/cache@v3
        with:
          path: ~/.julia/compiled
          key: compiled-${{ runner.os }}-${{ hashFiles('**/Project.toml') }}-${{ hashFiles('**/Manifest.toml') }}
          restore-keys: compiled-${{ runner.os }}-

      - name: Install package dependencies
        run: |
          julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'

      - name: Run tests
        run: |
          julia --project=. -e 'using Pkg; Pkg.test()'

